#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 21 20:22:17 2021

@author: alivaliyev
"""

class SparseArray():

  def __init__(self, n=0):
      self._arr = n*[0]

  def __setitem__(self, j, e):
      self._arr[j] = e

  def __getitem__(self, j):
      return self._arr[j]   
